### ISSUE TITLE
Is upgrade to Guzzle v7 planned?

### ISSUE THREAD

**Issue by C-Duv** [silktide/semrush-api#27]
Hello,

The version 7 of the `guzzlehttp/guzzle` package was [released in June 2020](https://github.com/guzzle/guzzle/releases/tag/7.0.0) and your `composer.json` locks the dependency to v6.x, do you plan to upgrade your code to use version 7.x?

Thanks

**Comment by dochne** [comment]
Hullo!

Looks like the BC's in 7 are irrelevant to our use of Guzzle in this repo, so I've just added some flexibility to the dependency.

Let me know if you have any issues!

**Comment by C-Duv** [comment]
Thanks! The package now installs just fine (I had other dependencies using Guzzle v7): I will now code some stuff to ~play with~ use it.
