### ISSUE TITLE
Unsetting on 'splitStringIntoArray($data)' failing.

### ISSUE THREAD

**Issue by mtio** [silktide/semrush-api#9]
In the ResponseParser.php file on line 109.

It takes in the response from the call to SemRush and explodes in on '\n'. 

Then unsets on the first index of the new exploded array. 

My expereince so far with the response from SemRush has been that the unset should happen on the last index, not the first. 

Code now:

![image](https://cloud.githubusercontent.com/assets/9405969/14263708/509491ce-fa79-11e5-9238-c14b84f37ff0.png)

![image](https://cloud.githubusercontent.com/assets/9405969/14263661/1c49f42c-fa79-11e5-879a-132ce278071c.png)

Code with edits:

![image](https://cloud.githubusercontent.com/assets/9405969/14263570/85be44e0-fa78-11e5-931c-52ba40c59440.png)

![image](https://cloud.githubusercontent.com/assets/9405969/14263591/9a8a2466-fa78-11e5-95b7-7325e0447f84.png)

**Comment by andywaite** [comment]
I think this row is to remove headers.  Can you provide the query you were doing so this can be looked at?
